import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/Footer";
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import Navbar from "@/components/Navbar";
config.autoAddCss = false

// const inter = Inter({ subsets: ["latin"] });
const benord = localFont({ src: '../public/fonts/Benord.otf' })

export const metadata: Metadata = {
  title: "Chemotronix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">    
      <body className={benord.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
